-- R10 deterministic setup
-- The policy master row alone does not create a duplicate claim.
-- Create an existing claim first, then submit another claim with the same:
-- policy number + patient + hospital + admission date.
--
-- If you intended CASE 10 to duplicate CASE 01, use POL-10001, not POL-10010.
--
-- Example prerequisite (adapt columns to your actual claims schema):
-- INSERT INTO public.claims (policy_number, patient_name, hospital_name, admission_date, ...)
-- VALUES ('POL-10001', 'Rahul Kumar', 'Manipal Hospital Bengaluru', '2026-04-10', ...);
--
-- Then upload CASE 10 with the same four values.
