CREATE TABLE IF NOT EXISTS policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id VARCHAR(50),
    policy_number VARCHAR(100) NOT NULL UNIQUE,
    policy_name VARCHAR(150),
    customer_name VARCHAR(150),
    carrier_name VARCHAR(150),
    start_date DATE,
    end_date DATE,
    sum_insured DECIMAL(15,2),
    status VARCHAR(20)
);
